plugins {
    id 'java'
    id 'application'
}

group = 'com.estacionamento'
version = '1.0'

application {
    mainClass = 'com.estacionamento.LicencaServer'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.45.1.0'
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveFileName = 'server.jar'
    manifest {
        attributes 'Main-Class': 'com.estacionamento.LicencaServer'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
